FROM golang:1.24 AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY api-keys.go utils.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -tags apikeys -o bootstrap api-keys.go utils.go

FROM public.ecr.aws/lambda/provided:al2023
COPY --from=builder /build/bootstrap /var/task/bootstrap
ENTRYPOINT ["/var/task/bootstrap"]
